### ISSUE TITLE
Enhance the check_names function because of "not a character" entities in the results

### ISSUE THREAD

**Issue by tommasobattisti** [gobbykid/gobbykid-text-analysis#6]
This issue is meant to host suggestions in terms of words and regex patterns to consider when the results have to be cleaned.

**Comment by eliarizzetto** [comment]
[output_01-08_characters_and_gender.txt](https://github.com/gobbykid/gobbykid-text-analysis/files/9235679/output_01-08_characters_and_gender.txt)

**Comment by tommasobattisti** [comment]
Leave a comment in form of:<br>
- The occurrence you have found in the results.
- The type of operation you want to perform on that occurrence (or similar ones); E.g. substring removal; substring replacement; avoid including strings that contain certain words; etc.

**Comment by tommasobattisti** [comment]
- "naval heroes"
- remove from the set the strings like /\w+\sheros?/

**Comment by tommasobattisti** [comment]
- "christmas eve"
- remove from the set the strings like /christmas\s\w+/

**Comment by tommasobattisti** [comment]
##Characters for book 1857_hughes-tom-browns-school-days

- "Gradus”: do not include (comes from Gradus ad Parnassum)
- “Robinson” is actually a family name
- “Fiddlesticks”: do not include
- “Box” is there, however it shouldn't since the word “Box” occurs many times in lowercase too (check if it's extracted with “'s” which is only then deleted)
- “Majesty”: do not include
- “Leicester”, “Oxford”, “Berkshire”, “Farringdon”: do not include
- “School”: do not include
- "Ashdown”: do not include (name of a place)
- “Canute” appear instead of “King Canute”

______________________________________________
To be finished...

**Comment by tommasobattisti** [comment]
### Results at the current state of the branch (August 3, 2022):
[output_01-08_characters_and_gender.txt](https://github.com/gobbykid/gobbykid-text-analysis/files/9249117/output_01-08_characters_and_gender.txt)

**Comment by tommasobattisti** [comment]
> ## Book 1857_browne-grannys-wonderful-chair:
> 
>     * “Majesty”: do not include
> 
>     * “Court”: do not include
> 
>     * “Royal Prince” and “Crown Prince”: do not include (do not include /w+\sprince(ss)?/ but include strings such as “Princess Jane” or “Prince Mark” )
> 
>     * “Michaelmas”: day of San Michael --> do not include
> 
>     * “Frostyface” retrieved only, while it's “Dame Frostyface” and the “Dame” before the name is actually useful to put the string in the list of feminine names
> 
>     * The same occurs for: “Greendalind”  (Princess Greendalind); “Wantall” (Queen Wantall); “Winwealth” (King Winwealth); “Greensleeves” (Lady Greensleeves); "Wisewit" (Prince Wisewit).

___________________________________________
SOLVED

**Comment by tommasobattisti** [comment]
## Book: 1888_wilde-the-happy-prince-and-other-tales.txt':
- “Logic”: do not include since it's not a character
- "Huzza”: do not include since it's an exclamation
- “Climb”: do not include
- “Cornish”: do not include (maybe with /w+ish/  ? so to automatically exclude also English, Scottish, etc.)
- “Wild Basil”: do not include
- “Gilly”: do not include
- “Crocuses”: do not include
- “Pylotechnic”: do not include
- “Echo”?

**Comment by tommasobattisti** [comment]
## Book: 1872_de-la-ramee-a-dog-of-flanders.txt:
- "Mechlin": do not include (from Mechlin lace)
- "Antwerp": do not include (it's a town)
- "Alvan": do not include
- "Christmas Eve": do not include
- "Daas", "Jehan" and "Jehan Daas" are the same character
- "Calvary", "Heaven" and "Hell": do not include
- "Kermesse", "Kyrie Eleison" and "Agni Dei": do not include
- "Ardennois": do not include and "Ardennoise Patrasche", only Patrasche is the name
- "Stavelot": do not include (it's a city)

**Comment by tommasobattisti** [comment]
## Book 1865_carroll-alices-adventures-in-wonderland.txt:

- "Grief": do not include
- "Hare" is a character. However "March hare" should be retrieved instead (this is not a real problem, just a caveat)
- "Geography": do not include
- "Latitude" and "Longitude": do not include
- "Collar": do not include
- "Footman" is retrieved but it appears many times in the text also as a lowercase word. It should be retrieved as "Frog Footman" or "Fish Footman" instead.
- "Beau": do not include (comes from "Beau-ootiful!")
_______________________________________________
TO BE COMPLETED

**Comment by eliarizzetto** [comment]
## CONTINUES: Book 1865_carroll-alices-adventures-in-wonderland.txt:

- "Grief": do not include
- "Hare" is a character. However "March hare" should be retrieved instead (this is not a real problem, just a caveat)
- "Geography": do not include
- "Latitude" and "Longitude": do not include
- "Collar": do not include
- "Footman" is retrieved but it appears many times in the text also as a lowercase word. It should be retrieved as "Frog Footman" or "Fish Footman" instead.
- "Beau": do not include (comes from "Beau-ootiful!")

----------------------------

#### Do NOT include: 
* "Kings"   (common noun)
* "Pray"    (verb)
* "Shy"     (exclamation)
* "Mystery" (common noun)
* "Ahem"    (exclamation)
* "Number One"  (common noun)
* "Latin Grammar"   (common noun)
* "Beautiful Soup"  (common noun)
* "Pennyworth"  (adjective)
* "Seaography"  (common noun)

#### Other operations:
* "Mock Turtle Soup" ---> just "Mock Turtle"
* "Cheshire Cat" = "Cheshire Puss" --> unify!
* "elsie lacie" comes from "Elsie, Lacie, and Tillie" --> do not include OR separate them (just 1 occurence)

* **MISSED DETECTION**: "Bill"   (15+ occurences)

**Comment by eliarizzetto** [comment]
## 1877_molesworth-the-cuckoo-clock

Either there's been some kind of error in pre-processing this text or it has been badly OCRed originally: words like "sothat", "hewas", "forit" originate from whitespaces being incorrectly eliminated. 

> **Warning**
> **Attention:MAKE SURE THE FILE YOU HAVE LOADED IN THE CORPUS YOU ARE USING IS THE CORRECT ONE, I.E. THE ONE BELOW**:
[The Cuckoo Clock](https://github.com/gobbykid/tm/blob/main/Corpus_selected_texts/female-writers/1877_molesworth-the-cuckoo-clock.txt)

**I have *just* changed it in my corpus, so you probably need to change it too!**

**Comment by eliarizzetto** [comment]
## 1877_sewell-black-beauty

Do NOT include:
- "Gee"       (exclamation)
- "Wells"     (city)
- "Lansdown"  (city)
- "Butcher"   (common name)
- "Hard Times My" (Chapter title + first word of paragraph)
- "Bishopsgate"   (city)
- "Earlshall" (city)
- "Fairstowe" (city)
- "Tattersall"    (city)
- "Birtwick"  (city) 

Other remarks:
- "Jerry Barker" = Jeremiah Barker
- "joe green joe green" --> Joe Green 
- "Langley" is not a female character, he's mentioned twice as "Captain Langley" and in the sentence "you are a military man, Langley"
- "Ginger One" = Ginger
- "Merrylegs" is a **male** horse
- "Filcher" is a man

**Comment by eliarizzetto** [comment]
>**Note**
>**New output file to check results against**

This is the output of run.py (character extraction + gender recognition) with a filtering threshold applied: the charEx function only returns words occurring uppercase only and **more than 2 times**.

[output_run_threshold2_090822.txt](https://github.com/gobbykid/gobbykid-text-analysis/files/9285520/output_run_threshold2_090822.txt)

**Comment by tommasobattisti** [comment]
> > Note
> > **New output file to check results against**
> 
> This is the output of run.py (character extraction + gender recognition) with a filtering threshold applied: the charEx function only returns words occurring uppercase only and **more than 2 times**.

_________________________________________
## Updated version:
[output_run_threshold2_090822.txt](https://github.com/gobbykid/gobbykid-text-analysis/files/9353645/output_run_threshold2_090822.txt)

**Comment by tommasobattisti** [comment]
## Related to the last version of the results: (Part I)

### Book: 1872_de-la-ramee-a-dog-of-flanders:
**Do not include:**
- “Antwerp”: City in Belgium
- "Mechlin”:  (from Mechlin lace)
- "Christmas eve”
- “Calvary”
- “Ardennois”
- "Kermesse”
____________________________________

### Book: 1857_browne-grannys-wonderful-chair:
- [x] Good

____________________________________

### Book: 1877_molesworth-the-cuckoo-clock:
** Do not include:**
- "Mandarine Land”: do not include strings having form “/\w+\sland/“
- “Merrybrow”: from "Merrybrow Hall”

**Other operations:**
- 'grizzel', 'aunt grizzel', 'sister grizzel', 'miss grizzel': the same character
- 'tabitha',  'sister tabitha', miss tabitha', 'aunt tabitha': the same character
- “Mwyne” is actually _“M'Swyne”_, the 's is deleted (maybe add something like “delete 's only when after the 's' a space occurr)
_____________________________________

### Book: 1902_potter-the-tale-of-peter-rabbit:
- [x] Good
_____________________________________

### Book: 1888_wilde-the-happy-prince-and-other-tales:
- “Huzza”: exclamation
- “Pylotechnic”
_____________________________________

### Book: 

**Do not include:**
- “Beau”: (comes from “Beau-ootiful!”)
- “Latitude” and “Longitude”
- “Pray” (verb)
- “Mystery” (common noun)
- "Soo”:  (from Soo-oop!)
- “Beautiful Soup” (common noun)

**Other:**
- MISSED DETECTION: “Bill” (15+ occurences)

_____________________________________

### Book: 1877_sewell-black-beauty
**Do not include:**
- "Duchess" and "Duke" alone (but consider them in the words that can determine the gender of the names)
- "Earlshall" (do not include strings like /\w+\s?hall/)
- "Birtwick" (city)

**Other remarks:**
- "Ginger One" should be "Ginger"


_____________________________________
## Other considerations not related to specific books:
It could be useful to not consider words that finish in _"ish”_ so to avoid including “English”, “Scottish”, etc.

**Comment by tommasobattisti** [comment]
## Related to the last version of the results: (Part III)

### Book: 1876_twain-the-adventures-of-tom-sawyer

**Do not include:**
- "Sabbath"
- "Hallo"
- "Missouri"
- "Texas"
- "Spaniard"
- "Sho"
- "Tom Sawyer's Gang"
- "St Petersburg"
- "Ting" from "Ting-a-ling-ling!"
- "Saturdays"

**Other remarks:**
- "Widow Douglas" should be female (add widow to the words that determine the gender)
_________________________________

### Book: 1883_stevenson-treasure-island

**Do not include:**
- "Bravo"
- "Scatter"
- "Avast"
- "Fontenoy"
- "Execution Dock"
- "Haylbowline Head" (place)
- "Lillibullero" (is a march)

**Other remarks:**
- "Long Johns" is actually "Long John's" and "Long John has been already retrieved
- "OBrien" is retrieved. In these cases, we should leave O'Brien
_____________________________________________

### Book: 1857_hughes-tom-browns-school-days

**Do not include:**
- "Fa" from "Fa-a-a-ag!"
- "Slogger"
- "Berks" (county)
- "Gradus" (dictionary)
- "Wessex" (kingdom)
- "Christian"
- "Manger"
- "Saxon"
- "Farringdon" (place)
- "Hullo"
- "Lawford" (path)
- "East" "West" etc.
- "Doctor"
- "Ashdown" (place)
- "Crew"
- "Peacock" (place?)
- "Triste"
- "Latin"
- "Bible"
- "School"
- "Huzza"
- "Bilton Grange" (place)
- "Great Western" (railway)
- "Avon" (river)
- "Pebbly Brook" (brook-->little stream)
- "Wellesburn" (village)
- "Wantage" (village)
- "Hazeldown" (place)
- "Balliol" (college)
- "Martinmas" (st Martin's day)
- "Himalayas"
- "Harkaway" (?)
- "Blawing Stwun (place)

_________________________________
## Further considerations:
- It could be useful to include only the words that appear at least once in uppercase not after a full stop, double quotes and ‘

**Comment by tommasobattisti** [comment]
## Related to the last version of the results: (Part IV)

### Book: 1869_dickens-david-copperfield

**Do not include:**
- "Ahem"
- "Aha"
- "Hark"
- "Humph"
- "Umph"
- "Thankee"
- "London" (It shouldn't be here)
- "Gravesen" (place)
- "Master"
- "Chatham" (place)
- "Doctor"
- "Memorial" and everything ending with it
- "Latin"
- "Blackheath" (area in London)
- "Lowestoft" (place)
- "Putney" (district in London)
- "Salem House"
- "Port Middlebay"
- "Covent Garden"
- "Good God"
- "Good Heaven"
- "Windsor Terrace"
- "Suffolk Punches" (equine race)
- "Camden Town"
- "Dear Agnes" (do not include /dear\s\.+/)
- "Westminister Abbey"
- "Won't" (it should be Won't)
- "Sundays"
- "Beein" (?)
- "Cookery Book"
- "Yarmouth" (place)
- "Blunderstone Rookery" (place)

**Other remarks:**
- 'mr copperfield', 'master copperfield', "mr david copperfield" etc. are the same character
- "Twenty Seven" = "Number Twenty Seven"
- "Larkins" should be "Miss Larkins" or "Mr. Larkins"

**Comment by tommasobattisti** [comment]
## Done:
- [x] 1872_de-la-ramee-a-dog-of-flanders

**Comment by tommasobattisti** [comment]
## Minor common problems:

### 1877_molesworth-the-cuckoo-clock
'grizzel', 'aunt grizzel', 'sister grizzel', 'miss grizzel': the same character
'tabitha', 'sister tabitha', miss tabitha', 'aunt tabitha': the same character

**Comment by tommasobattisti** [comment]
## General imporovements:
- Consider: "Mr Higgs", "Higgs", "Mrs Higgs". If we remove "Higgs" we should not lose any information and our results should be better.
